# **Inteligencia Artificial con Aplicaciones en Economía I**

- 👩‍🏫 **Profesora:** [Lina María Castro](https://www.linkedin.com/in/lina-maria-castro)  
- 📧 **Email:** [lmcastroco@gmail.com](mailto:lmcastroco@gmail.com)  
- 🎓 **Universidad:** Universidad Externado de Colombia - Facultad de Economía

# **Taller Limpieza y transformación de datos**🧹

**IMPORTANTE**: Guarda una copia de este notebook en tu Google Drive o computador.

**Taller en grupos de 3 o parejas.**

**Nombres estudiantes:**

-Daniel Alejandro Caicedo Ballen

**Forma de entrega:**

- Nombrar el archivo de la siguiente forma:“Taller_Limpieza_nombres_y_appellidos.ipynb”.
- Suba el Jupyter Notebook a su cuenta en Github y envíe el link en el siguiente Forms: https://forms.office.com/r/6GZ89uiLNC.

**IMPORTANTE:** No se recibirán talleres en Google Colab, el notebook debe estar subido en Github.

**Plazo de entrega:**

19 de marzo de 2026, máximo a las 11:59 p.m. Tenga en cuenta que luego de esa hora el formulario en forms se cierra. El Jupupyter Notebook también debe quedar subido en Github antes de esa hora.

**Instrucciones Generales:**

Completa el código en las celdas marcadas con `### TU CÓDIGO AQUÍ ###`. Puedes añadir más celdas si lo requieres.

Utilice la base de la GEIH de julio a diciembre de 2025, la cual se encuentra en https://drive.google.com/drive/folders/1Th4TWdsOahAAvBUKxixFhaELC_KPsl3y?usp=sharing. Tenga en cuenta sep="," y encoding='latin1'. Las variables 'DPTO' y 'RAMA4D_R4' deben ser cargadas como string.

# Ejercicio 1: Importar librerías y cargar datos

1.	Importe todas las librerías que vaya a utilizar.

In [ ]:
import pandas as pd
import numpy as np
import os
from google.colab import drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

2.	Mejore la visualización de los dataframes como se ha visto en clase.

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', '{:.2f}'.format)

3.	Conéctese a su Google Drive y establezca la ruta del dataset.

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

4.	Cargue los datos en el notebook. Llame al dataframe 'df_geih'

In [ ]:
ruta =  "/content/drive/MyDrive/datasets/GEIH_2025_Jul_Dic_Consolidado.csv"
df_geih = pd.read_csv(ruta, sep=",", encoding="latin-1", low_memory=False)

5. Obtenga las dimensiones de la base

In [ ]:
df_geih.shape

(409127, 314)

# Ejercicio 2:  Seleccionar y renombrar columnas

La GEIH contiene cientos de variables. Para nuestro análisis del mercado laboral, nos enfocaremos en un subconjunto.

Adicionalmente, los nombres de las columnas en la GEIH son códigos. Para hacer el análisis más intuitivo, vamos a renombrarlas.

1. Crea un nuevo DataFrame llamado `df_empleo` que contenga únicamente las columnas que están en la lista `columnas_interes`.

In [ ]:
columnas_interes = ['DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'MES', 'CLASE', 'DPTO', 'FEX_C18', 'PT', 'P3271', 'P6040', 'P6080', 'P3043', 'OCI',
                    'P6430', 'RAMA4D_R4', 'INGLABO', 'DESCRIPCION_CIIU', 'NOMBRE_DPTO']

In [ ]:
df_empleo=df_geih[columnas_interes]
df_empleo

,DIRECTORIO,SECUENCIA_P,ORDEN,MES,CLASE,DPTO,FEX_C18,PT,P3271,P6040,P6080,P3043,OCI,P6430,RAMA4D_R4,INGLABO,DESCRIPCION_CIIU,NOMBRE_DPTO
0,8283143,1,1,7,2,8,27.75,1,1,72,6,NaN,1.00,7.00,143.00,790000.00,Cría de ovejas y cabras,ATLÁNTICO
1,8283143,1,2,7,2,8,27.75,1,2,34,6,NaN,NaN,NaN,NaN,NaN,NaN,ATLÁNTICO
2,8283145,1,1,7,2,8,59.11,1,1,45,6,NaN,1.00,1.00,141.00,1100000.00,Cría de ganado bovino y bufalino,ATLÁNTICO
3,8283145,1,2,7,2,8,59.11,1,2,50,6,NaN,NaN,NaN,NaN,NaN,NaN,ATLÁNTICO
4,8283145,1,3,7,2,8,59.11,1,1,19,6,NaN,1.00,7.00,141.00,820000.00,Cría de ganado bovino y bufalino,ATLÁNTICO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409122,8473907,1,1,12,2,73,378.31,1,2,61,6,NaN,1.00,3.00,9700.00,1400000.00,Actividades de los hogares individuales como e...,TOLIMA
409123,8473908,1,1,12,1,54,534.55,1,1,58,6,9.00,1.00,2.00,8530.00,3000000.00,Establecimientos que combinan diferentes nivel...,NORTE DE SANTANDER
409124,8473908,1,2,12,1,54,534.55,1,2,51,6,9.00,1.00,2.00,8412.00,7956000.00,Actividades ejecutivas de la administración pú...,NORTE DE SANTANDER
409125,8473908,1,3,12,1,54,534.55,1,2,31,6,7.00,NaN,NaN,NaN,NaN,NaN,NORTE DE SANTANDER
409126,8473908,1,4,12,1,54,534.55,1,2,26,6,7.00,1.00,4.00,4791.00,500000.00,Comercio al por menor realizado a través de in...,NORTE DE SANTANDER

2. Renombra las columnas del DataFrame `df_empleo` utilizando el diccionario `mapa_nombres`.

In [ ]:
mapa_nombres = {
'DIRECTORIO': 'id_vivienda',
'SECUENCIA_P': 'id_hogar',
'ORDEN': 'id_persona',
'MES': 'mes',
'CLASE': 'clase',
'DPTO': 'departamento',
'FEX_C18': 'factor_expansion',
'PT': 'poblacion_total',
'P3271': 'sexo',
'P6040': 'edad',
'P6080': 'grupo_etnico',
'P3043': 'nivel_educativo',
'OCI': 'ocupados',
'P6430': 'categoria_ocupacional',
'RAMA4D_R4': 'cod_ciiu',
'INGLABO': 'ingreso_laboral',
'DESCRIPCION_CIIU': 'desc_ciiu',
'NOMBRE_DPTO': 'nombre_dpto'}

In [ ]:
df_empleo = df_empleo.rename(columns=mapa_nombres)
df_empleo

,id_vivienda,id_hogar,id_persona,mes,clase,departamento,factor_expansion,poblacion_total,sexo,edad,grupo_etnico,nivel_educativo,ocupados,categoria_ocupacional,cod_ciiu,ingreso_laboral,desc_ciiu,nombre_dpto
0,8283143,1,1,7,2,8,27.75,1,1,72,6,NaN,1.00,7.00,143.00,790000.00,Cría de ovejas y cabras,ATLÁNTICO
1,8283143,1,2,7,2,8,27.75,1,2,34,6,NaN,NaN,NaN,NaN,NaN,NaN,ATLÁNTICO
2,8283145,1,1,7,2,8,59.11,1,1,45,6,NaN,1.00,1.00,141.00,1100000.00,Cría de ganado bovino y bufalino,ATLÁNTICO
3,8283145,1,2,7,2,8,59.11,1,2,50,6,NaN,NaN,NaN,NaN,NaN,NaN,ATLÁNTICO
4,8283145,1,3,7,2,8,59.11,1,1,19,6,NaN,1.00,7.00,141.00,820000.00,Cría de ganado bovino y bufalino,ATLÁNTICO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409122,8473907,1,1,12,2,73,378.31,1,2,61,6,NaN,1.00,3.00,9700.00,1400000.00,Actividades de los hogares individuales como e...,TOLIMA
409123,8473908,1,1,12,1,54,534.55,1,1,58,6,9.00,1.00,2.00,8530.00,3000000.00,Establecimientos que combinan diferentes nivel...,NORTE DE SANTANDER
409124,8473908,1,2,12,1,54,534.55,1,2,51,6,9.00,1.00,2.00,8412.00,7956000.00,Actividades ejecutivas de la administración pú...,NORTE DE SANTANDER
409125,8473908,1,3,12,1,54,534.55,1,2,31,6,7.00,NaN,NaN,NaN,NaN,NaN,NORTE DE SANTANDER
409126,8473908,1,4,12,1,54,534.55,1,2,26,6,7.00,1.00,4.00,4791.00,500000.00,Comercio al por menor realizado a través de in...,NORTE DE SANTANDER

3. Obtenga las dimensiones de la base

In [ ]:
df_empleo.shape

(409127, 18)

# Ejercicio 3: Revisión de duplicados

Un paso crucial en la limpieza es asegurar que no haya observaciones duplicadas que puedan sesgar nuestro análisis.

1. Verifica si hay filas duplicadas en `df_empleo`.

In [ ]:
df_empleo.duplicated().any()

np.False_

2. Cuenta cuántas filas duplicadas existen.

In [ ]:
df_empleo.duplicated().sum()

np.int64(0)

3. Elimina las filas duplicadas, si las hay.

In [ ]:

df_empleo = df_empleo.drop_duplicates()

4. Verifica si hay filas duplicadas específicamente en las columnas 'id_vivienda', 'id_hogar', 'id_persona'.

In [ ]:
df_empleo.duplicated(subset=["id_vivienda", "id_hogar", "id_persona"]).any()

np.False_

# Ejercicio 4: Valores faltantes

Los datos del mundo real raramente están completos. Aquí, trataremos los valores faltantes en la columna de ingresos.

1. Calcula el número de valores nulos (`NaN`) en la columna `ingreso_laboral` **antes** de cualquier modificación.

In [ ]:
df_empleo["ingreso_laboral"].isna().sum()

np.int64(231144)

2. En la GEIH, un ingreso faltante a menudo significa que la persona no reportó ingresos o no aplica (ej. no trabaja). Una estrategia común es imputar estos valores con `0`. Rellena los valores `NaN` en la columna `ingreso_laboral` con `0`.

In [ ]:
df_empleo["ingreso_laboral"] = df_empleo["ingreso_laboral"].fillna(0)

# Ejercicio 5: Decodificar variables

Las variables categóricas a menudo necesitan ser "traducidas" para hacerlas más entendibles para el análisis.

1. Usa los siguientes diccionarios para reemplazar los códigos numéricos por etiquetas de texto en las siguientes columnas: 'clase', 'sexo', 'grupo_etnico', 'nivel_educativo' y 'categoria_ocupacional'. Muestra los conteos de las nuevas categorías usando `.value_counts()` para verificar el cambio en cada una de las columnas.

In [ ]:
dic_clase = {1: 'Cabeceras', 2: 'Centros poblados y rural disperso'}
dic_sexo = {1: 'Hombre', 2: 'Mujer'}
dic_etnico = {1: 'Indígena', 2: 'Gitano (Rom)', 3: 'Raizal del archipiélago', 4: 'Palenquero',
              5: 'Negro, mulato (afrodescendiente)', 6: 'Ninguno de los anteriores'}
dic_nivel_educativo = {1: 'Ninguno', 2: 'Educación media', 3: 'Educación media',
                       4: 'Educación media', 5: 'Técnica profesional', 6: 'Tecnológica',
                       7: 'Universitaria', 8: 'Especialización', 9: 'Maestría',
                       10: 'Doctorado', 99: 'No sabe, no informa'}
dic_cat_ocu = {1: 'Asalariado', 2: 'Asalariado', 3: 'Asalariado',
               8: 'Asalariado', 4: 'Independiente', 5: 'Independiente',
               9: 'Independiente', 6: 'Trabajador sin remuneración',
               7: 'Trabajador sin remuneración'}

In [ ]:
df_empleo["clase"]=df_empleo["clase"].replace(dic_clase)

In [ ]:
df_empleo["sexo"]=df_empleo["sexo"].replace(dic_sexo)

In [ ]:
df_empleo["grupo_etnico"]=df_empleo["grupo_etnico"].replace(dic_etnico)

/tmp/ipykernel_286/287867208.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_empleo["grupo_etnico"]=df_empleo["grupo_etnico"].replace(dic_etnico)

In [ ]:
df_empleo["nivel_educativo"]=df_empleo["nivel_educativo"].replace(dic_nivel_educativo)

/tmp/ipykernel_286/1867761713.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_empleo["nivel_educativo"]=df_empleo["nivel_educativo"].replace(dic_nivel_educativo)

In [ ]:
df_empleo["categoria_ocupacional"]=df_empleo["categoria_ocupacional"].replace(dic_cat_ocu)

/tmp/ipykernel_286/2998401472.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df_empleo["categoria_ocupacional"]=df_empleo["categoria_ocupacional"].replace(dic_cat_ocu)

In [ ]:
print(df_empleo["clase"].value_counts())
print(df_empleo["sexo"].value_counts())
print(df_empleo["grupo_etnico"].value_counts())
print(df_empleo["nivel_educativo"].value_counts())
print(df_empleo["categoria_ocupacional"].value_counts())

clase
Cabeceras                            356377
Centros poblados y rural disperso     52750
Name: count, dtype: int64
sexo
2    218597
1    190530
Name: count, dtype: int64
grupo_etnico
6    350562
5     39032
1     18420
3       925
4       120
2        68
Name: count, dtype: int64
nivel_educativo
2.00     105634
7.00      32517
5.00      24503
1.00      12963
6.00      10640
3.00      10358
8.00       7927
9.00       3154
4.00        643
10.00       339
99.00         1
Name: count, dtype: int64
categoria_ocupacional
4.00    78369
1.00    76483
2.00     9365
3.00     6083
7.00     4404
5.00     4129
6.00     2935
8.00       85
Name: count, dtype: int64

# Ejercicio 6: Reorganizar columnas

1. Reorganiza las columnas con el siguiente orden: 'id_vivienda', 'id_hogar', 'id_persona', 'mes', 'clase', 'departamento', 'nombre_dpto',     'factor_expansion', 'poblacion_total', 'sexo', 'edad', 'grupo_etnico', 'nivel_educativo', 'ocupados', 'categoria_ocupacional', 'cod_ciiu', 'desc_ciiu', 'ingreso_laboral'

In [ ]:
orden_columnas=[ 'id_vivienda', 'id_hogar', 'id_persona', 'mes', 'clase', 'departamento', 'nombre_dpto', 'factor_expansion', 'poblacion_total', 'sexo', 'edad', 'grupo_etnico', 'nivel_educativo', 'ocupados', 'categoria_ocupacional', 'cod_ciiu', 'desc_ciiu', 'ingreso_laboral']
df_empleo = df_empleo[orden_columnas]

In [ ]:
df_empleo

,id_vivienda,id_hogar,id_persona,mes,clase,departamento,nombre_dpto,factor_expansion,poblacion_total,sexo,edad,grupo_etnico,nivel_educativo,ocupados,categoria_ocupacional,cod_ciiu,desc_ciiu,ingreso_laboral
0,8283143,1,1,7,Centros poblados y rural disperso,8,ATLÁNTICO,27.75,1,1,72,6,NaN,1.00,7.00,143.00,Cría de ovejas y cabras,790000.00
1,8283143,1,2,7,Centros poblados y rural disperso,8,ATLÁNTICO,27.75,1,2,34,6,NaN,NaN,NaN,NaN,NaN,0.00
2,8283145,1,1,7,Centros poblados y rural disperso,8,ATLÁNTICO,59.11,1,1,45,6,NaN,1.00,1.00,141.00,Cría de ganado bovino y bufalino,1100000.00
3,8283145,1,2,7,Centros poblados y rural disperso,8,ATLÁNTICO,59.11,1,2,50,6,NaN,NaN,NaN,NaN,NaN,0.00
4,8283145,1,3,7,Centros poblados y rural disperso,8,ATLÁNTICO,59.11,1,1,19,6,NaN,1.00,7.00,141.00,Cría de ganado bovino y bufalino,820000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409122,8473907,1,1,12,Centros poblados y rural disperso,73,TOLIMA,378.31,1,2,61,6,NaN,1.00,3.00,9700.00,Actividades de los hogares individuales como e...,1400000.00
409123,8473908,1,1,12,Cabeceras,54,NORTE DE SANTANDER,534.55,1,1,58,6,9.00,1.00,2.00,8530.00,Establecimientos que combinan diferentes nivel...,3000000.00
409124,8473908,1,2,12,Cabeceras,54,NORTE DE SANTANDER,534.55,1,2,51,6,9.00,1.00,2.00,8412.00,Actividades ejecutivas de la administración pú...,7956000.00
409125,8473908,1,3,12,Cabeceras,54,NORTE DE SANTANDER,534.55,1,2,31,6,7.00,NaN,NaN,NaN,NaN,0.00
409126,8473908,1,4,12,Cabeceras,54,NORTE DE SANTANDER,534.55,1,2,26,6,7.00,1.00,4.00,4791.00,Comercio al por menor realizado a través de in...,500000.00

# Ejercicio 7: Cambiar tipo de dato

Para realizar cálculos y análisis correctamente, las columnas deben tener el tipo de dato adecuado (numérico, categórico, etc.).

1.  Muestra en pantalla los tipos de datos actuales de `df_empleo`.

In [ ]:
df_empleo.dtypes

id_vivienda                int64
id_hogar                   int64
id_persona                 int64
mes                        int64
clase                     object
departamento               int64
nombre_dpto               object
factor_expansion         float64
poblacion_total            int64
sexo                       int64
edad                       int64
grupo_etnico               int64
nivel_educativo          float64
ocupados                 float64
categoria_ocupacional    float64
cod_ciiu                 float64
desc_ciiu                 object
ingreso_laboral          float64
dtype: object

2.  Las siguientes columnas representan categorías: 'clase', 'departamento', 'nombre_dpto', 'sexo', 'grupo_etnico', 'nivel_educativo', 'categoria_ocupacional', 'cod_ciiu', 'desc_ciiu'. Conviértelas al tipo `category` para optimizar el uso de memoria y facilitar análisis futuros.

In [ ]:
columnas_categoricas=['clase', 'departamento', 'nombre_dpto', 'sexo', 'grupo_etnico', 'nivel_educativo', 'categoria_ocupacional', 'cod_ciiu', 'desc_ciiu']
for i in columnas_categoricas:
    df_empleo[i]=df_empleo[i].astype("category")

# Ejercicio 8: Ordenar el dataframe (5%)

1. Ordena el dataframe por la columna "edad" de mayor a menor. Observa la columna 'edad' y escribe en una celda de markdown cuál fue la edad mínima y la edad máxima de las personas que respondieron la encuesta de la GEIH.

In [ ]:
df_empleo = df_empleo.sort_values(by="edad", ascending=False)

In [ ]:
edad_max=df_empleo["edad"].max()
edad_min=df_empleo["edad"].min()
print("Edad máxima:", edad_max)
print("Edad mínima:", edad_min)

Edad máxima: 108
Edad mínima: 0

Escribe tu análisis aquí:
Dentro de la encuesta se puede evidenciar que hay presencia de personas bastante longevas que superan el umbral de los 100 años, asi como de recien nacidos que aun no completan el año

# Ejercicio 9: Groupby

Agrupar los datos por categorías, nos permite realizar análisis más profundos y obtener insights valiosos, que a simple vista no vemos en la base de datos.

1. Crea un nuevo dataframe llamado "df_sexo" donde se agrupe por 'sexo' y se calcule la suma de las columnas 'poblacion_total' y 'ocupados'. Crea una nueva columna que se llame 'porcentaje_ocupados' donde dividas las columna 'ocupados' sobre 'poblacion_total'. Al final usa reset_index() para convertir las categorías de sexo en una columna.

In [ ]:
df_sexo = df_empleo.groupby("sexo")[["poblacion_total", "ocupados"]].sum()

/tmp/ipykernel_286/3890120058.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_sexo = df_empleo.groupby("sexo")[["poblacion_total", "ocupados"]].sum()

In [ ]:
df_sexo["porcentaje_ocupados"] = df_sexo["ocupados"] / df_sexo["poblacion_total"]

In [ ]:
df_sexo = df_sexo.reset_index()

2. Crea un nuevo dataframe llamado "df_educacion" donde se agrupe por 'nivel_educativo' y se calcule la suma de las columnas 'poblacion_total' y 'ocupados'. Crea una nueva columna que se llame 'porcentaje_ocupados' donde dividas las columna 'ocupados' sobre 'poblacion_total'. Al final usa reset_index() para convertir las categorías de nivel educativo en una columna.

In [ ]:
df_educacion = df_empleo.groupby("nivel_educativo")[["poblacion_total", "ocupados"]].sum()

/tmp/ipykernel_286/788364756.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_educacion = df_empleo.groupby("nivel_educativo")[["poblacion_total", "ocupados"]].sum()

In [ ]:
df_educacion["porcentaje_ocupados"] = df_educacion["ocupados"] / df_educacion["poblacion_total"]

In [ ]:
df_educacion = df_educacion.reset_index()

3. En una celda de Markdown escribe qué conclusiones puedes sacar de la información obtenida en df_sexo y df_educacion.

Escribe tu análisis aquí:

# Ejercicio 10: Filtrar datos

1. A partir de df_empleo, crea el DataFrame `df_ing` con observaciones donde `ingreso_laboral` no sea nulo y además sea mayor estrictamente al salario mínimo para 2026 (con subsidio de transporte).

In [ ]:
salario_min=2000000
df_ing = df_empleo[df_empleo["ingreso_laboral"] > salario_min]

2. ¿Cuántas personas tienen un salario estrictamente mayor al salario mínimo?

In [ ]:
df_ing.shape[0]

38093

3. Crea el dataframe df_mujeres donde se encuentren solamente mujeres que están ubicadas en el departamento del Tolima, que son asalariadas y cuyo nivel educativo es educación media o superior.

In [ ]:
df_mujeres = df_empleo[
    (df_empleo["sexo"] == "Mujer") &
    (df_empleo["nombre_dpto"] == "TOLIMA") &
    (df_empleo["categoria_ocupacional"] == "Asalariado") &
    (df_empleo["nivel_educativo"].isin([
        "Educación media",
        "Técnica profesional",
        "Tecnológica",
        "Universitaria",
        "Especialización",
        "Maestría",
        "Doctorado"
    ]))
]

4. ¿Cuáles son las dimensiones de df_mujeres?

In [ ]:
df_mujeres.shape

(1137, 18)